import {
  API_PATH,
  GRAPHQL_PATH,
  GRAPHQL_SUBSCRIPTIONS_PATH
} from 'react-native-dotenv'

export default {
  API_PATH: API_PATH,
  GRAPHQL_PATH: GRAPHQL_PATH,
  GRAPHQL_SUBSCRIPTIONS_PATH: GRAPHQL_SUBSCRIPTIONS_PATH
}
